/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ZVUK */

#ifndef _Included_ZVUK
#define _Included_ZVUK
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     ZVUK
	 * Method:    printHelloWorld
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_ZVUK_printHelloWorld
	(JNIEnv*, jobject);

	/*
	 * Class:     ZVUK
	 * Method:    readLastMeasure
	 * Signature: ()[I
	 */
	JNIEXPORT jintArray JNICALL Java_ZVUK_readLastMeasure
	(JNIEnv*, jobject);

	/*
	 * Class:     ZVUK
	 * Method:    open
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_ZVUK_open
	(JNIEnv*, jobject);

	/*
	 * Class:     ZVUK
	 * Method:    close
	 * Signature: (I)V
	 */
	JNIEXPORT void JNICALL Java_ZVUK_close
	(JNIEnv*, jobject, jint);

	/*
	 * Class:     ZVUK
	 * Method:    getMeasure
	 * Signature: (II)I
	 */
	JNIEXPORT jint JNICALL Java_ZVUK_getMeasure
	(JNIEnv*, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
